Path:
  LatestLog:
    dc: 'log_data/dc.csv'
    hpcs: 'log_data/hpcs.csv'
    biomus: 'log_data/bb-dl.csv'
    pssp: 'log_data/pssp.csv'
  PrevLog:
    dc: 'prev_log/dc.csv'
    hpcs: 'prev_log/hpcs.csv'
    biomus: 'prev_log/bb-dl.csv'
    pssp: 'prev_log/pssp.csv'

Socket:
  HOST: 'localhost'
  PORT: 30001